version: '3.8'

services:
  mysql:
    container_name: ${PROJECT_NAME}_mysql
    image: percona:latest
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - '${PROJECT_HOST}:${MYSQL_PORT}:${MYSQL_PORT}'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  postgres:
    container_name: ${PROJECT_NAME}_postgres
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init/postgres:/docker-entrypoint-initdb.d:ro
    ports:
      - '${PROJECT_HOST}:${POSTGRES_PORT}:${POSTGRES_PORT}'
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGPORT: "$POSTGRES_PORT"
      PGUSER: "$POSTGRES_USER"
      PGPASSWORD: "$POSTGRES_PASSWORD"
      PGDATA: /var/lib/postgresql/data/pgdata

volumes:
  mysql-data: { }
  postgres-data: { }
